version: '3'

services:

  ecommerce-service:
    build:
      context: ./../ecommerce-service
      dockerfile: ./../ecommerce-service/ecommerce-service.dockerfile
    ports:
      - "8081:80"
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=ecommerce sslmode=disable timezone=UTC connect_timeout=5"

  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: "replicated"
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
